version: '3'
services:
  postgres:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}	
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

